### ISSUE TITLE
Use VcfAnnotateConsequence to partially replace VEP

### ISSUE THREAD

**Issue by marc-sturm** [imgag/megSAP#130]
## TODO
- [x] Test VcfAnnotateConsquence against VEP output
  - [x] Test HGVS c. and p. annotation
  - [x] Test exon/intron numbering
  - [x] Test impact
  - [x] Test type
- [x] implement multi-threaded version of VcfAnnotateConsequence
- [x] benchmark and compare to VEP
- [x] create ngs-bits release with final version of VcfAnnotateConsequence
- [x] use in megSAP
  - [x] convert REVEL to VCF and annotate it using VcfAnnotateFromVcf
  - [x] deploy megSAP version after nightly tests run through

## Benchmarks
Details in /mnt/users/ahsturm1/Sandbox/2022_11_17_VcfAnnotateConsequence_benchmarks/

Comparison to VEP on WES (NA12878_58) and WGS (NA12878_45)
|                                                          | WES  |  WGS  |
| --------------------------------------|-------|--------|
| VEP (1 thread)                                   | 490s  | 7623s |
| VcfAnnotateConsequence (1 thread)  | 35s | 234s |

Benchmarks multi-threaded on WGS (NA12878_45)
|                                                          |  WGS  |
| --------------------------------------|--------|
| VcfAnnotateConsequence (1 thread)  | 4:35s |
| VcfAnnotateConsequence (2 thread)  | 2:38s |
| VcfAnnotateConsequence (4 thread)  | 1:56s |
| VcfAnnotateConsequence (8 thread)  | 1:24s |

**Note:** VcfAnnotateConsequence  has a 20 sec offset for loading the GFF file which does not speed up.

Benchmarks of VEP:
![grafik](https://user-images.githubusercontent.com/5638144/203058287-6fb986cd-74e5-44f6-b007-0ddedd7d9752.png)

![grafik](https://user-images.githubusercontent.com/5638144/203776897-c457fb0d-be7e-40b8-83be-4611fe373065.png)

**Note:** PubMed, REVEL and Regulatory are the longest annotation. Try to replace them...
